In [2]:
!pip install hmmlearn

In [3]:
# Definisi Matrik Transisi (states)

states = ('Rainy', 'Sunny')
 
# definisi Matriks Observasi / Matrik emmisi    
observations = ('walk', 'shop', 'clean')

# definisi Matriks Priority
start_probability = {'Rainy': 0.6, 'Sunny': 0.4}
 
transition_probability = {
   'Rainy' : {'Rainy': 0.7, 'Sunny': 0.3},
   'Sunny' : {'Rainy': 0.4, 'Sunny': 0.6},
   }
 
emission_probability = {
   'Rainy' : {'walk': 0.1, 'shop': 0.4, 'clean': 0.5},
   'Sunny' : {'walk': 0.6, 'shop': 0.3, 'clean': 0.1},
   }

In [4]:
# Library untuk HMM
# Cara install pip install hmmlearn==0.2.2

from hmmlearn import hmm
import numpy as np

model = hmm.MultinomialHMM(n_components=2)
model.startprob_ = np.array([0.6, 0.4])
model.transmat_ = np.array([[0.7, 0.3],
                            [0.4, 0.6]])
model.emissionprob_ = np.array([[0.1, 0.4, 0.5],
                                [0.6, 0.3, 0.1]])


In [11]:
# Given a known model what is the likelihood of sequence O happening?
# The probability of the first observation being “Walk” equals to the multiplication 
# of the initial state distribution and emission probability matrix.
# 0.6 x 0.1 + 0.4 x 0.6 = 0.30 (30%). 
# The log likelihood is provided from calling .score.
# catatan {'walk', 'shop','clean' }
# Kasus untuk initial state #
# contoh untuk observasi 'walk' 
# peluang dari model jika observasi adalah 'walk'
# 0.6 x 0.1 + 0.4 x 0.6 = 0.30 (30%)

import math 
math.exp(model.score(np.array([[0]])))

0.30000000000000004

In [12]:
# contoh untuk observasi 'shop' 
# peluang dari model jika observasi adalah 'shop'
# 0.6 x 0.4 + 0.4 x 0.3 = (36%)

math.exp(model.score(np.array([[1]])))

0.36000000000000004

In [6]:
# contoh untuk observasi 'clean' 
# peluang dari model jika observasi adalah 'clean'
# 0.6 x 0.5 + 0.4 x 0.1 = (34%)

math.exp(model.score(np.array([[2]])))


0.3400000000000001

In [8]:
# contoh untuk observasi {'clean', 'clean'} 
# peluang dari model jika observasi {'clean', 'clean'} adalah
math.exp(model.score(np.array([[2,2]])))

0.1244

In [9]:
#==== HMM decode dengan algoritma viterbi di dalamnya ======#
logprob, seq = model.decode(np.array([[1,2,0]]).transpose())
print(math.exp(logprob))
print(seq)

0.015120000000000003
[0 0 1]


In [10]:
logprob, seq = model.decode(np.array([[2,2,2]]).transpose())
print(math.exp(logprob))
print(seq)

0.03674999999999999
[0 0 0]


Hitung peluang dari model jika observasi {'clean', 'clean',’walk’, ‘walk’, ‘shop’} dari model yang ada


In [13]:
math.exp(model.score(np.array([[2,2,0,0,1]])))

0.004082395400000001

Catat state yang paling  baik untuk untuk observasi {'clean', 'clean',’walk’, ‘walk’, ‘shop’} dari model yang ada

In [14]:
logprob, seq = model.decode(np.array([[2,2,0,0,1]]).transpose())
print(math.exp(logprob))
print(seq)

0.001224720000000001
[0 0 1 1 1]


# Kesimpulan:
1. Peluang {'clean', 'clean',’walk’, ‘walk’, ‘shop’} adalah 0.00408 atau sekitar 0,408%
2. State yang paling baik untuk obeservasi {'clean', 'clean',’walk’, ‘walk’, ‘shop’} adalah pada saat {Rainy, Rainy, Sunny, Sunny} dengan peluang sebesar 0.00122 atau 0.122%